### ISSUE TITLE
Will u a add a license to the book?

### ISSUE THREAD

**Issue by sofish** [restcookbook/restcookbook#50]
Hi Joshua. It's a good read to start with REST API, and i would love to translate it into Chinese. Only for the purpose to spread it as an open-source book. I'm wondering if i need any kind of permission.

**Comment by jaytaph** [comment]
I've added a CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) license to the articles. That should be enough for you to create an open-source book (non-commercially).

**Comment by sofish** [comment]
Gotcha, it's enough :+1:
